export class fdTraxClm {
  public static COLUMNFORDETAILS = [
    'edit',
    'delete',
    "tin_no",
    "bu_type",
    "sub_brk_cd",
    "euin_no",
    'fd_bu_type',
    "company_type_name",
    "comp_full_name",
    "comp_short_name",
    "scheme_name",
    "investor_name",
    "investor_pan",
    "kyc_status",
    "option",
    "sub_option",
    "tenure_type",
    "tenure",
    'interest_rate',
    "maturity_instruction",
    "amount",
    "mode_of_transaction",
    'chq_bank',
    'acc_no',
    'payment_ref_no',
    'chq_no',
    "certificate_delivery_opt",
    "tds_info",
    "comp_login_at"
  ];
  public static COLUMN_SELECTOR = [
    {id:'edit',text: 'Edit'},
    {id:'delete',text: 'Delete'},
    {id:"tin_no",text: 'TIN No'},
    {id:"bu_type",text: 'Buisness Type'},
    {id:"sub_brk_cd",text: 'Sub Broker Code'},
    {id:"euin_no",text: 'Employee'},
    {id:'fd_bu_type',text:'Fixed Deposit Buisness Type'},
    {id:"company_type_name",text:"Company Type"},
    {id:"comp_full_name",text:"company Full Name"},
    {id:"comp_short_name",text:"company Short Name"},
    {id:"scheme_name",text:"Scheme Name"},
    {id:"investor_name",text:"Investor Name"},
    {id:"kyc_status",text:"KYC Status"},
    {id:"option",text:"Option"},
    {id:"sub_option",text:"Sub Option"},
    {id:"tenure_type",text:"Tenure Type"},
    {id:"tenure",text:"Tenure"},
    {id:"interest_rate",text:"Interest Rate"},
    {id:"maturity_instruction",text:"Maturity Instruction"},
    {id:"amount",text:"Amount"},
    {id:"mode_of_transaction",text:"Mode Of Transaction"},
    {id:"chq_bank",text:"Bank Name"},
    {id:"acc_no",text:"Account Number"},
    {id:"payment_ref_no",text:"Payment Reference Number"},
    {id:"chq_no",text:"Cheque Number"},
    {id:"certificate_delivery_opt",text:"Certificate Delivery Option"},
    {id:"tds_info",text:"TDS Information"},
    {id:"comp_login_at",text:"Company Login_ At"}
  ];
  public static INITIAL_COLUMNS = [
    'edit',
    'delete',
    "tin_no",
    "bu_type",
    "sub_brk_cd",
    "euin_no"
  ];

  public static Columns =
      [
        {field:'edit',header:'Edit',isVisible:[1,2]},
        {field:'app_form_scan',header:'DOC View',isVisible:[1,2]},
        {field:'entry_date',header:'Entry Date',isVisible:[1,2,3]},
        {field:'comp_login_cutt_off',header:'Login Cut Off',isVisible:[1,2]},
        {field:'comp_login_dt',header:'Login Date',isVisible:[1,2]},
        {field:'tin_no',header:'TIN',isVisible:[1,2,3]},
        {field:'bu_type',header:'Business Type',isVisible:[1,2,3]},
        {field:'branch_name',header:'Branch',isVisible:[1,2,3]},
        {field:'rm_name',header:'RM Name',isVisible:[1]},
        {field:'sub_brk_cd',header:'Sub Broker Code',isVisible:[1,2,3]},
        {field:'emp_name',header:'Employee',isVisible:[1,2,3]},
        {field:'investor_name',header:'First Holder Name',isVisible:[1,2,3]},
        {field:'investor_code',header:'First Holder Code',isVisible:[1,2,3]},
        {field:'investor_pan',header:'First Holder PAN',isVisible:[1,2,3]},
        {field:'investor_kyc_status',header:'First Holder KYC Status',isVisible:[1]},
        {field:'mode_of_holding',header:'Mode Of Holding',isVisible:[1]},
        {field:'investor_name_2',header:'Second Holder Name',isVisible:[1]},
        {field:'investor_code_2',header:'Second Holder Code',isVisible:[1]},
        {field:'investor_pan_2',header:'Second Holder PAN',isVisible:[1]},
        {field:'investor_kyc_status_2',header:'Third Holder KYC Status',isVisible:[1]},
        {field:'investor_name_3',header:'Third Holder Name',isVisible:[1]},
        {field:'investor_code_3',header:'Third Holder Code',isVisible:[1]},
        {field:'investor_pan_3',header:'Third Holder PAN',isVisible:[1]},
        {field:'investor_kyc_status_3',header:'Third Holder KYC Status',isVisible:[1]},
        {field:'company_type_name',header:'Company Type',isVisible:[1]},
        {field:'investment_type',header:'Investment Type',isVisible:[1,2,3]},
        {field:'scheme_name',header:'Scheme',isVisible:[1,2,3]},
        {field:'comp_short_name',header:'Company',isVisible:[1,2,3]},
        {field:'option',header:'Option',isVisible:[1,2,3]},
        {field:'sub_option',header:'Sub Option',isVisible:[1]},
        {field:'tenure_type',header:'Tenure Type',isVisible:[1]},
        {field:'maturity_date',header:'Maturity Date',isVisible:[1,2,3]},
        {field:'interest_rate',header:'Tenure Interset Rate',isVisible:[1,2,3]},
        {field:'maturity_instruction',header:'Maturity Instruction',isVisible:[1]},
        {field:'amount',header:'Amount',isVisible:[1,2,3]},
        {field:'mode_of_payment',header:'Transaction Mode',isVisible:[1,2,3]},
        {field:'bank_name',header:'Bank',isVisible:[1]},
        {field:'acc_no',header:'Account No',isVisible:[1]},
        {field:'payment_ref_no',header:'Payment Ref No',isVisible:[1]},
        {field:'chq_no',header:'Cheque No',isVisible:[1]},
        {field:'application_no',header:'Application No',isVisible:[1]},
        {field:'fdr_no',header:'FDR No',isVisible:[1]},
        {field:'certificate_delivery_opt',header:'Certification Delivery Option',isVisible:[1]},
        {field:'tds_info_name',header:'TDS',isVisible:[1]},
        {field:'comp_login_name',header:'Login At',isVisible:[1,2,3]},
        {field:'remarks',header:'remarks',isVisible:[1]}

      ]
}
