export class clientColumns {
  public static EXISTING_CLIENT = [
    'edit',
    'delete',
    'sl_no',
    'client_name',
    'cl_type',
    'pan',
  ];
  public static MINOR_CLIENT = [
    'edit',
    'delete',
    'sl_no',
    'client_code',
    'client_name',
    'cl_type',
    'dob',
    'dob_actual',
    'guardians_pan',
    'guardians_name',
    'relation',
    'mobile',
    'sec_mobile',
    'email',
    'sec_email',
    'add_line_1',
    'add_line_2',
    'state',
    'dist',
    'city',
    'pincode',
  ];
  public static PAN_HOLDER_CLIENT = [
    'edit',
    'delete',
    'sl_no',
    'client_code',
    'client_name',
    'cl_type',
    'pan',
    'dob',
    'dob_actual',
    'anniversary_date',
    'mobile',
    'sec_mobile',
    'email',
    'sec_email',
    'add_line_1',
    'add_line_2',
    'state',
    'dist',
    'city',
    'pincode',
  ];
  public static NON_PAN_HOLDER_CLIENT = [
    'edit',
    'delete',
    'sl_no',
    'client_code',
    'client_name',
    'cl_type',
    'dob',
    'dob_actual',
    'anniversary_date',
    'mobile',
    'sec_mobile',
    'email',
    'sec_email',
    'add_line_1',
    'add_line_2',
    'state',
    'dist',
    'city',
    'pincode',
  ];
  public static COLUMN_SELECTOR = [
    { id: 'edit', text: 'Edit' },
    { id: 'delete', text: 'Delete' },
    { id: 'sl_no', text: 'Sl No' },
    { id: 'client_code', text: 'Client Code' },
    { id: 'client_name', text: 'Client Name' },
    { id: 'cl_type', text: 'Client Type' },
    { id: 'pan', text: 'PAN' },
    { id: 'dob', text: 'Date Of Birth' },
    { id:"anniversary_date",text: 'Anniversary Date'},
    { id: 'dob_actual', text: 'Actual Date Of Birth' },
    { id: 'guardians_pan', text: 'Gurdians PAN' },
    { id: 'guardians_name', text: 'Gurdians Name' },
    { id: 'relation', text: 'Relation' },
    { id: 'mobile', text: 'Mobile' },
    { id: 'sec_mobile', text: 'Alternative Mobile' },
    { id: 'email', text: 'Email' },
    { id: 'sec_email', text: 'Alternative Email' },
    { id: 'add_line_1', text: 'Address-1' },
    { id: 'add_line_2', text: 'Address-2' },
    { id: 'state', text: 'State' },
    { id: 'dist', text: 'District' },
    { id: 'city', text: 'City' },
    { id: 'pincode', text: 'Picode' },
  ];

  public static INITIAL_COLUMNS = [
    'edit',
    'delete',
    'sl_no',
    'client_code',
    'client_name',
    'cl_type',
    'pan'
  ]

}
