export class cmpMstClm {
  public static COLUMNFORDETAILS = [
    'edit',
    'delete',
    'sl_no',
    'ins_type',
    'comp_full_name',
    'comp_short_name',
    'website',
    'cus_care_whatsApp_no',
    'cus_care_no',
    'cus_care_email',
    'distributor_care_no',
    'distributor_care_email',
    'head_ofc_contact_per',
    'head_contact_per_mobile',
    'head_contact_per_email',
    'head_ofc_addr',
    'local_ofc_contact_per',
    'local_contact_per_mobile',
    'local_contact_per_email',
    'local_ofc_addr',
    'login_url',
    'login_id',
    'login_pass',
    'l1_name',
    'l1_email',
    'l1_contact_no',

    'l2_name',
    'l2_email',
    'l2_contact_no',

    'l3_name',
    'l3_email',
    'l3_contact_no',

    'l4_name',
    'l4_email',
    'l4_contact_no',

    'l5_name',
    'l5_email',
    'l5_contact_no',

    'l6_name',
    'l6_email',
    'l6_contact_no',
  ];
  public static COLUMN_SELECTOR = [
    { id: 'edit', text: 'Edit' },
    { id: 'delete', text: 'Delete' },
    { id: 'sl_no', text: 'Sl No' },
    { id: 'ins_type', text: 'Insurance Type' },
    { id: 'comp_full_name', text: 'Company Full name' },
    { id: 'comp_short_name', text: 'Company Short Name' },
    { id: 'website', text: 'Website' },
    { id: 'cus_care_whatsApp_no', text: 'Customer Care WhatsApp Number' },
    { id: 'cus_care_no', text: 'Customer Care Number' },
    { id: 'cus_care_email', text: 'Customer Care Email' },
    {id:'distributor_care_no',text:'Distributor Care Number'},
    {id:'distributor_care_email',text:'Distributor Care Email'},
    { id: 'head_ofc_contact_per', text: 'Head Office Contact Person' },
    {id: 'head_contact_per_mobile',text: 'Head Office Contact Person Mobile',},
    { id: 'head_contact_per_email', text: 'Head Office Contact Person Email'},
    { id: 'head_ofc_addr', text: 'Head Office Contact Person Address'},
    { id: 'local_ofc_contact_per', text: 'Local Office Contact Person'},
    {id: 'local_contact_per_mobile',text: 'Local Office Contact Person Mobile',},
    {id: 'local_contact_per_email',text: 'Local Office Contact Person Email'},
    {id: 'local_ofc_addr',text: 'Local Office Contact Person Address'},
    { id: 'login_url', text: 'Login URL' },
    { id: 'login_id', text: 'Login ID' },
    { id: 'login_pass', text: 'Login Password' },
    {id:'l1_name',text:'Level-1 Name'},
    {id:'l1_email',text:'Level-1 Email'},
    {id:'l1_contact_no',text:'Level-1 Contact Number'},
    {id:'l2_name',text:'Level-2 Name'},
    {id:'l2_email',text:'Level-2 email'},
    {id:'l2_contact_no',text:'Level-2 Contact Number'},
    {id:'l3_name',text:'Level-3 Name'},
    {id:'l3_email',text:'Level-3 Email'},
    {id:'l3_contact_no',text:'Level-3 Contact Number'},
    {id:'l4_name',text:'Level-4 Name'},
    {id:'l4_email',text:'Level-4 Email'},
    {id:'l4_contact_no',text:'Level-4 Contact Number'},
    {id:'l5_name',text:'Level-5 Name'},
    {id:'l5_email',text:'Level-5 Email'},
    {id:'l5_contact_no',text:'Level-5 Contact Number'},
    {id:'l6_name',text:'Level-6 Name'},
    {id:'l6_email',text:'Level-6 Email'},
    {id:'l6_contact_no',text:'Level-6 Contact Number'},
  ];
  public static INITIAL_COLUMNS = [
    'edit',
    'delete',
    'sl_no',
    'ins_type',
    'comp_full_name',
    'comp_short_name'
  ];
  public static LEVELS = [
    {name:1,value:"Level-1(Operation)"},
    {name:2,value:"Level-2(Operation Head)"},
    {name:3,value:"Level-3(RM - Sales)"},
    {name:4,value:"Level-4(Area Manager/Regional Manager)"},
    {name:5,value:"Level-5(Zonal Manager/State Head)"},
    {name:6,value:"Level-6(National Sales Head/Product Head)"}
  ]
  public static l1 = [ 'l1_name','l1_email','l1_contact_no']
  public static l2 = [ 'l2_name','l2_email','l2_contact_no']
  public static l3 = [ 'l3_name','l3_email','l3_contact_no']
  public static l4 = [ 'l4_name','l4_email','l4_contact_no']
  public static l5 = [ 'l5_name','l5_email','l5_contact_no']
  public static l6 = [ 'l6_name','l6_email','l6_contact_no']
  public static MODIFIEDCLM =  [   'edit',
                                    'delete',
                                    'sl_no',
                                    'ins_type',
                                    'comp_full_name',
                                    'comp_short_name',
                                    'website',
                                    'cus_care_whatsApp_no',
                                    'cus_care_no',
                                    'cus_care_email',
                                    'distributor_care_no',
                                    'distributor_care_email',
                                    'head_ofc_contact_per',
                                    'head_contact_per_mobile',
                                    'head_contact_per_email',
                                    'head_ofc_addr',
                                    'local_ofc_contact_per',
                                    'local_contact_per_mobile',
                                    'local_contact_per_email',
                                    'local_ofc_addr',
                                    'login_url',
                                    'login_id',
                                    'login_pass'
                                  ]

}
