import { column } from "src/app/__Model/tblClmns";

export class insTraxClm {
  public static COLUMNFORDETAILS = [
    'edit',
    'delete',
    "tin_no",
    "bu_type",
    "sub_brk_cd",
    "euin_no",
    'insure_bu_type',
    "ins_type",
    "proposer_code",
    "proposer_name",
    "proposer_pan",
    "insured_person_code",
    "insured_person_name",
    "insured_person_pan",
    "comp_full_name",
    "comp_short_name",
    "product_type",
    "product_name",
    "proposal_no",
    "sum_assured",
    "mode_of_premium",
    "gross_premium",
    "net_premium",
    "mode_of_payment",
    'acc_no',
    "chq_bank",
    "chq_no",
    "payment_ref_no",
    "comp_login_at",
    "entry_date",
    "policy_pre_pay_term",
    "policy_term"

  ];
  public static COLUMN_SELECTOR = [
    {id:'edit',text: 'Edit'},
    {id:'delete',text: 'Delete'},
    {id:"tin_no",text: 'TIN No'},
    {id:"bu_type",text: 'Buisness Type'},
    {id:"sub_brk_cd",text: 'Sub Broker Code'},
    {id:"euin_no",text: 'Employee'},
    {id:'insure_bu_type',text: 'Insured Buisness Type'},
    {id:"ins_type",text: 'Insurance Type'},
    {id:"proposer_code",text: 'Proposer Code'},
    {id:"proposer_name",text: 'Proposer Name'},
    {id:"proposer_pan",text: 'Proposer PAN'},
    {id:"insured_person_code",text: 'Insured Person Code'},
    {id:"insured_person_name",text: 'Insured Person Name'},
    {id:"insured_person_pan",text: 'Insured Person PAN'},
    {id:"comp_full_name",text: 'Company Full Name'},
    {id:"comp_short_name",text: 'Company Short Name'},
    {id:"product_type",text: 'Product Type'},
    {id:"product_name",text: 'Product Name'},
    {id:"proposal_no",text: 'Proposal No'},
    {id:"sum_assured",text: 'Sum Assured'},
    {id:"mode_of_premium",text: 'Mode Of Premium'},
    {id:"gross_premium",text: 'Gross Premium'},
    {id:"net_premium",text: 'Net Premium'},
    {id:"mode_of_payment",text: 'Mode Of Payment'},
    {id:'acc_no',text: 'Account No'},
    {id:"chq_bank",text: 'Bank'},
    {id:"chq_no",text: 'Cheque No'},
    {id:"payment_ref_no",text: 'Payment Reference No'},
    {id:"entry_date",text: 'Entry Date'},
    {id:"policy_term",text:'policy Term'},
    {id:"policy_pre_pay_term",text: 'Policy Premium Paying Term'},
    {id:"comp_login_at",text: 'Login At'},
  ];

  public static INITIAL_COLUMNS = [
    'edit',
    'delete',
    "tin_no",
    "bu_type",
    "sub_brk_cd",
    "euin_no"
  ]

  public static Columns = [
    {field:'edit',header:'Edit',isVisible:[1,2]},
    {field:'ins_application_form',header:'DOC View',isVisible:[1,2]},
    {field:'entry_date',header:'Entry Date',isVisible:[1,2,3]},
    {field:'comp_login_cutt_off',header:'Login Cut Off',isVisible:[1]},
    {field:'comp_login_dt',header:'Login Date',isVisible:[1]},
    {field:'tin_no',header:'TIN',isVisible:[1,2,3]},
    {field:'bu_type',header:'Business Type',isVisible:[1,2,3]},
    {field:'branch_name',header:'Branch',isVisible:[1,2,3]},
    {field:'rm_name',header:'RM Name',isVisible:[1]},
    {field:'sub_brk_cd',header:'Sub Broker Code',isVisible:[1,2,3]},
    {field:'emp_name',header:'Employee',isVisible:[1,2,3]},
    {field:'proposer_name',header:'Proposer Name',isVisible:[1,2,3]},
    {field:'proposer_code',header:'Proposer Code',isVisible:[1]},
    {field:'proposer_pan',header:'Proposer PAN',isVisible:[1]},
    {field:'insured_person_name',header:'Insured Person Name',isVisible:[1,2,3]},
    {field:'insured_person_code',header:'Insured Person Code',isVisible:[1]},
    {field:'insured_person_pan',header:'Insured Person PAN',isVisible:[1]},
    {field:'ins_type',header:'Type Of Insurance',isVisible:[1,2,3]},
    {field:'comp_short_name',header:'Company',isVisible:[1,2,3]},
    {field:'product_type',header:'Product Type',isVisible:[1,3]},
    {field:'product_name',header:'Product Name',isVisible:[1,2,3]},
    {field:'insure_bu_type',header:'Insurance Business Type',isVisible:[1,2,3]},
    {field:'proposal_no',header:'Proposal No',isVisible:[1,2,3]},
    {field:'policy_no',header:'Policy No',isVisible:[1,2,3]},
    {field:'sum_assured',header:'Sum Assured / Insured',isVisible:[1]},
    {field:'mode_of_premium',header:'Mode Of Premium',isVisible:[1]},
    {field:'gross_premium',header:'Gross Premium',isVisible:[1,2,3]},
    {field:'net_premium',header:'Net Premium',isVisible:[1]},
    {field:'mode_of_payment',header:'Mode Of Payment',isVisible:[1,2,3]},
    {field:'acc_no',header:'Account No',isVisible:[1]},
    {field:'chq_bank',header:'Bank',isVisible:[1]},
    {field:'chq_no',header:'Cheque No',isVisible:[1]},
    {field:"payment_ref_no",header: 'Payment Ref No',isVisible:[1]},
    {field:"policy_pre_pay_term",header: 'Policy Premium Paying Term',isVisible:[1]},
    {field:"policy_term",header: 'Policy Term',isVisible:[1]},
    {field:"comp_login_at",header: 'Login At',isVisible:[1,2,3]},
    {field:"remarks",header: 'Remarks',isVisible:[1]}
  ]


  public static renewal_Columns:column[]= [
    {field:"edit",header: 'Edit'},
    {field:'upload_file',header:'DOC View'},
    {field:'temp_tin_no',header:'Temporary TIN'},
    {field:"bu_type",header: 'business Type'},
    {field:'branch_name',header:'Branch'},
    {field:'rm_name',header:'RM Name'},
    {field:"sub_brk_cd",header: 'Sub Broker Code'},
    {field:"emp_name",header: 'Employee'},
    {field:'proposer_name',header:'Proposer Name'},
    {field:'proposer_code',header:'Proposer Code'},
    {field:'proposer_pan',header:'Proposer PAN'},
    {field:'ins_type',header:'Type Of Insurance'},
    {field:'insured_person_name',header:'Insured Person Name'},
    {field:'insured_person_code',header:'Insured Person Code'},
    {field:'insured_person_pan',header:'Insured Person PAN'},
    {field:'comp_short_name',header:'Company'},
    {field:'product_type',header:'Product Type'},
    {field:'product_name',header:'Product Name'},
    {field:'sum_insured',header:'Sum Insured'},
    {field:'renewal_dt',header:'Renewal Date'},
    {field:'remarks',header:'Remarks'}
  ]
}
