export class insTraxClm {
  public static COLUMNFORDETAILS = [
    'edit',
    'delete',
    "tin_no",
    "bu_type",
    "arn_no",
    "euin_no",
    'insure_bu_type',
    "ins_type",
    "proposer_code",
    "proposer_name",
    "proposer_pan",
    "proposer_type",
    "insured_person_code",
    "insured_person_name",
    "insured_person_pan",
    "insured_person_type",
    "comp_full_name",
    "comp_short_name",
    "product_type",
    "product_name",
    "proposal_no",
    "sum_assured",
    "mode_of_premium",
    "gross_premium",
    "net_premium",
    "mode_of_payment",
    'acc_no',
    "chq_bank",
    "chq_no",
    "payment_ref_no",
    "comp_login_at",
    "entry_date",
    "policy_pre_pay_term",
    "policy_term"

  ];
  public static COLUMN_SELECTOR = [
    {id:'edit',text: 'Edit'},
    {id:'delete',text: 'Delete'},
    {id:"tin_no",text: 'TIN No'},
    {id:"bu_type",text: 'Buisness Type'},
    {id:"arn_no",text: 'ARN No'},
    {id:"euin_no",text: 'EUIN'},
    {id:'insure_bu_type',text: 'Insured Buisness Type'},
    {id:"ins_type",text: 'Insurance Type'},
    {id:"proposer_code",text: 'Proposer Code'},
    {id:"proposer_name",text: 'Proposer Name'},
    {id:"proposer_pan",text: 'Proposer PAN'},
    {id:"proposer_type",text: 'Proposer Type'},
    {id:"insured_person_code",text: 'Insured Person Code'},
    {id:"insured_person_name",text: 'Insured Person Name'},
    {id:"insured_person_pan",text: 'Insured Person PAN'},
    {id:"insured_person_type",text: 'Insured Person Type'},
    {id:"comp_full_name",text: 'Company Full Name'},
    {id:"comp_short_name",text: 'Company Short Name'},
    {id:"product_type",text: 'Product Type'},
    {id:"product_name",text: 'Product Name'},
    {id:"proposal_no",text: 'Proposal No'},
    {id:"sum_assured",text: 'Sum Assured'},
    {id:"mode_of_premium",text: 'Mode Of Premium'},
    {id:"gross_premium",text: 'Gross Premium'},
    {id:"net_premium",text: 'Net Premium'},
    {id:"mode_of_payment",text: 'Mode Of Payment'},
    {id:'acc_no',text: 'Account No'},
    {id:"chq_bank",text: 'Bank'},
    {id:"chq_no",text: 'Cheque No'},
    {id:"payment_ref_no",text: 'Payment Reference No'},
    {id:"entry_date",text: 'Entry Date'},
    {id:"policy_term",text:'policy Term'},
    {id:"policy_pre_pay_term",text: 'Policy Premium Paying Term'},
    {id:"comp_login_at",text: 'Login At'},
  ];

  public static INITIAL_COLUMNS = [
    'edit',
    'delete',
    "tin_no",
    "bu_type",
    "arn_no",
    "euin_no"
  ]
}
