export class amcClmns {
  public static DETAILS = [
    'edit',
    'delete',
    'sl_no',
    'logo',
    'amc_name',
    'amc_short_name',
    'rnt_name',
    'gstin',
    'website',
    'cus_care_whatsapp_no',
    'cust_care_number',
    'cust_care_email',
    'distributor_care_no',
    'distributor_care_email',
    'head_ofc_contact_per',
    'head_contact_per_mob',
    'head_contact_per_email',
    'head_ofc_addr',
    'local_ofc_contact_per',
    'local_contact_per_mob',
    'local_contact_per_email',
    'local_ofc_addr',
    'login_url',
    'login_id',
    'login_pass',
    'l1_name',
    'l1_email',
    'l1_contact_no',
    'l2_name',
    'l2_email',
    'l2_contact_no',
    'l3_name',
    'l3_email',
    'l3_contact_no',
    'l4_name',
    'l4_email',
    'l4_contact_no',
    'l5_name',
    'l5_email',
    'l5_contact_no',
    'l6_name',
    'l6_email',
    'l6_contact_no',
  ];

  public static SUMMARY = [
    'edit',
    'delete',
    'sl_no',
    'logo',
    'amc_name',
    'amc_short_name',
    'rnt_name'
  ]

  public static COLUMNSELECTOR = [
      {id:'edit',text:'Edit'},
      {id:'delete',text:'Delete'},
      {id:'sl_no',text:'Sl No'},
      {id:'logo',text:'Logo'},
      {id:'amc_name',text:'AMC Full Name'},
      {id:'amc_short_name',text:'AMC Short Name'},
      {id:'rnt_name',text:'R&T'},
      {id:"gstin",text:"GSTIN"},
      {id:'website',text:'Website'},
      {id:'cus_care_whatsapp_no',text:'Customer Care WhatsApp Number'},
      {id:'distributor_care_no',text:'Distributor Care Number'},
      {id:'distributor_care_email',text:'Distributor Care Email'},
      {id:'cust_care_email',text:'Customer Care Email'},
      {id:'head_ofc_contact_per',text:'Head Contact Person Name'},
      {id:'head_contact_per_mob',text:'Head Contact Person Mobile'},
      {id:'head_contact_per_email',text:'Head Contact Person Email'},
      {id:'head_ofc_addr',text:'Head Office Address'},
      {id:'local_ofc_contact_per',text:'Local Contact Person Name'},
      {id:'local_contact_per_mob',text:'Local Contact Person Mobile'},
      {id:'local_contact_per_email',text:'Local Contact Person Email'},
      {id:'local_ofc_addr',text:'Local Office Address'},
      {id:'login_url',text:'Login URL'},
      {id:'login_id',text:'Login ID'},
      {id:'login_pass',text:'Login Password'},
      {id:'l1_name',text:'Level-1 Name'},
      {id:'l1_email',text:'Level-1 Email'},
      {id:'l1_contact_no',text:'Level-1 Contact Number'},
      {id:'l2_name',text:'Level-2 Name'},
      {id:'l2_email',text:'Level-2 email'},
      {id:'l2_contact_no',text:'Level-2 Contact Number'},
      {id:'l3_name',text:'Level-3 Name'},
      {id:'l3_email',text:'Level-3 Email'},
      {id:'l3_contact_no',text:'Level-3 Contact Number'},
      {id:'l4_name',text:'Level-4 Name'},
      {id:'l4_email',text:'Level-4 Email'},
      {id:'l4_contact_no',text:'Level-4 Contact Number'},
      {id:'l5_name',text:'Level-5 Name'},
      {id:'l5_email',text:'Level-5 Email'},
      {id:'l5_contact_no',text:'Level-5 Contact Number'},
      {id:'l6_name',text:'Level-6 Name'},
      {id:'l6_email',text:'Level-6 Email'},
      {id:'l6_contact_no',text:'Level-6 Contact Number'},
  ];

}
