export class rntClmns{
  public static SUMMARY = [
    {field:'edit',header:"Edit"},
    {field:'delete',header:"Delete"},
    {field:'sl_no',header:"Sl No"},
    {field:'rnt_name',header:"R&T Short Name"},
    {field:'rnt_full_name',header:"R&T Full Name"},
    {field:'website',header:"Website"},
    {field:'cus_care_whatsApp_no',header:"Customer Care Whatsapp No"},
    {field:'cus_care_no',header:"Customer Care No"},
    {field:'cus_care_email',header:"Customer Care Email"},
  ];

  public static DETAILS = [
    { field: 'edit', header: 'Edit' },
    { field: 'delete', header: 'Delete' },
    { field: 'sl_no', header: 'Sl No' },
    { field: 'logo', header: 'Logo' },
    { field: 'rnt_name', header: 'R&T Short name'},
    { field: 'rnt_full_name', header: 'R&T Full Name'},
    { field: 'website', header: 'Website' },
    { field: 'cus_care_whatsApp_no', header: 'Customer Care WhatsApp Number' },
    { field: 'cus_care_no', header: 'Customer Care Number' },
    { field: 'cus_care_email', header: 'Customer Care Email' },
    { field: 'distributor_care_email', header: 'Distributor Care Email' },
    { field: 'distributor_care_no', header: 'Distributor Care Number' },
    { field: 'head_ofc_contact_per', header: 'Head Office Contact Person' },
    {field: 'head_contact_per_mobile',header: 'Head Office Contact Person Mobile',},
    { field: 'head_contact_per_email', header: 'Head Office Contact Person Email' },
    { field: 'head_ofc_addr', header: 'Head Office Contact Person Address' },
    { field: 'local_ofc_contact_per', header: 'Local Office Contact Person' },
    {field: 'local_contact_per_mobile',header: 'Local Office Contact Person Mobile',},
    {field: 'local_contact_per_email',header: 'Local Office Contact Person Email',},
    {field: 'local_ofc_addr',header: 'Local Office Contact Person Address',},
    { field: 'login_url', header: 'Login URL'},
    { field: 'login_id', header: 'Login ID'},
    { field: 'login_pass', header: 'Login Password'},
    {field:'l1_name',header:'Level-1 Name'},
    {field:'l1_email',header:'Level-1 Email'},
    {field:'l1_contact_no',header:'Level-1 Contact Number'},
    {field:'l2_name',header:'Level-2 Name'},
    {field:'l2_email',header:'Level-2 Email'},
    {field:'l2_contact_no',header:'Level-2 Contact Number'},
    {field:'l3_name',header:'Level-3 Name'},
    {field:'l3_email',header:'Level-3 Email'},
    {field:'l3_contact_no',header:'Level-3 Contact Number'},
    {field:'l4_name',header:'Level-4 Name'},
    {field:'l4_email',header:'Level-4 Email'},
    {field:'l4_contact_no',header:'Level-4 Contact Number'},
    {field:'l5_name',header:'Level-5 Name'},
    {field:'l5_email',header:'Level-5 Email'},
    {field:'l5_contact_no',header:'Level-5 Contact Number'},
    {field:'l6_name',header:'Level-6 Name'},
    {field:'l6_email',header:'Level-6 Email'},
    {field:'l6_contact_no',header:'Level-6 Contact Number'},
  ]
}
