import { column } from "src/app/__Model/tblClmns";

export class schemeClmns{
  public static column_selector:column[]=[
    {field: "edit",header:"Edit",width:'8rem'},
    {field: "delete",header:"Delete",width:'8rem'},
    {field: "scheme_name",header:"Scheme",width:'25rem'},
    {field: "scheme_type",header:"Scheme Type",width:'10rem'},
    {field: "amc_short_name",header:"AMC",width:'15rem'},
    {field: "cat_name",header:"Category",width:'10rem'},
    {field: "subcate_name",header:"Sub Category",width:'10rem'},
    {field: "nfo_start_dt",header:"NFO Start Date",width:'10rem'},
    {field: "nfo_end_dt",header:"NFO End Date",width:'10rem'},
    {field: "nfo_reopen_dt",header:"NFO Reopen Date",width:'10rem'},
    {field:'sip_allowed',header:'SIP Allowed',width:'8rem'},
    {field:'sip_date',header:'SIP Dates',width:'25rem'},
    {field:'purchase_allowed',header:'Purchase Allowed',width:'8rem'},
    {field: "pip_fresh_min_amt",header:"Fresh Amount (PIP)",width:'12rem'},
    {field: "pip_add_min_amt",header:"Additional Amount (PIP)",width:'12rem'},
    {field: "pip_multiple_amount",header:"Multiple Amount (PIP)",width:'12rem'},
    {field:"special_sip_name",header:'Special SIP',width:'12rem'},
    {field:'swp_allowed',header:'SWP Allowed',width:'8rem'},
    {field:"swp_date",header:'SWP Dates',width:'25rem'},
    {field:'stp_allowed',header:'STP Allowed',width:'8rem'},
    {field:'stp_date',header:'STP Dates',width:'25rem'},
    {field:'D_sip_min_F_amount',header:'Daily SIP Fresh Minimum Amount',width:'10rem'},
    {field:'D_sip_min_A_amount',header:'Daily SIP Additional Minimum Amount',width:'10rem'},
    {field:'W_sip_min_F_amount',header:'Weekly SIP Fresh Minimum Amount',width:'10rem'},
    {field:'W_sip_min_A_amount',header:'Weekly SIP Additional Minimum Amount',width:'10rem'},
    {field:'F_sip_min_F_amount',header:'Fortnightly SIP Fresh Minimum Amount',width:'10rem'},
    {field:'F_sip_min_A_amount',header:'Fortnightly SIP Additional Minimum Amount',width:'10rem'},
    {field:'M_sip_min_F_amount',header:'Monthly SIP Fresh Minimum Amount',width:'10rem'},
    {field:'M_sip_min_A_amount',header:'Monthly SIP Additional Minimum Amount',width:'10rem'},
    {field:'Q_sip_min_F_amount',header:'Quarterly SIP Fresh Minimum Amount',width:'10rem'},
    {field:'Q_sip_min_A_amount',header:'Quarterly SIP Additional Minimum Amount',width:'10rem'},
    {field:'S_sip_min_F_amount',header:'Semi Anually SIP Fresh Minimum Amount',width:'10rem'},
    {field:'S_sip_min_A_amount',header:'Semi Anually SIP Additional Minimum Amount',width:'10rem'},
    {field:'A_sip_min_F_amount',header:'Anually SIP Fresh Minimum Amount',width:'10rem'},
    {field:'A_sip_min_A_amount',header:'Anually SIP Additional Minimum Amount',width:'10rem'},
    {field:'D_swp_min_amount',header:'Daily SWP Amount',width:'10rem'},
    {field:'W_swp_min_amount',header:'Weekly SWP Amount',width:'10rem'},
    {field:'F_swp_min_amount',header:'Fortnightly SWP Amount',width:'10rem'},
    {field:'M_swp_min_amount',header:'Monthly SWP Amount',width:'10rem'},
    {field:'Q_swp_min_amount',header:'Quarterly SWP Amount',width:'10rem'},
    {field:'S_swp_min_amount',header:'Semi Anually SWP Amount',width:'10rem'},
    {field:'A_swp_min_amount',header:'Anually SWP Amount',width:'10rem'},
    {field:'D_stp_min_amount',header:'Daily STP Amount',width:'10rem'},
    {field:'W_stp_min_amount',header:'Weekly STP Amount',width:'10rem'},
    {field:'F_stp_min_amount',header:'Fortnightly STP Amount',width:'10rem'},
    {field:'M_stp_min_amount',header:'Monthly STP Amount',width:'10rem'},
    {field:'Q_stp_min_amount',header:'Quarterly STP Amount',width:'10rem'},
    {field:'S_stp_min_amount',header:'Semi Anually STP Amount',width:'10rem'},
    {field:'A_stp_min_amount',header:'Anually STP Amount',width:'10rem'},
    {field:'switch_allowed',header:'Switch Allowed',width:'8rem'},
    {field:'switch_mul_amt',header:'Switch In Multiple Amount',width:'10rem'},
    {field:'switch_min_amt',header:'Switch In Minimum Amount',width:'10rem'},
    {field:'exit_load',header:'Exit Load',width:'15rem'},
    {field:'benchmark',header:'Benchmark',width:'10rem'},
    {field:'tax_implication',header:'Tax Implication',width:'10rem'}
  ]
  public static Summary:column[] = [
    {field: "edit",header:"Edit",width:'8rem'},
    {field: "delete",header:"Delete",width:'8rem'},
    {field: "scheme_name",header:"Scheme",width:'25rem'},
    {field: "scheme_type",header:"Scheme Type",width:'10rem'},
    {field: "amc_short_name",header:"AMC",width:'15rem'},
    {field:'purchase_allowed',header:'Purchase Allowed',width:'8rem'},
    {field:'sip_allowed',header:'SIP Allowed',width:'10rem'},
    {field:'swp_allowed',header:'SWP Allowed',width:'10rem'},
    {field:'stp_allowed',header:'STP Allowed',width:'10rem'},
    {field:'switch_allowed',header:'Switch Allowed',width:'12rem'},
    {field:'exit_load',header:'Exit Load',width:'15rem'},
    {field:'benchmark',header:'Benchmark',width:'10rem'},
    {field:'tax_implication',header:'Tax Implication',width:'10rem'}
  ]
}

export class ISINClmns{
 public static Columns:column[] = [
  {field:'edit',header:'Edit'},
  {field:'delete',header:'Delete'},
  {field:'amc_short_name',header:'AMC'},
  {field:'cat_name',header:'Category'},
  {field:'subcategory_name',header:'Subcategory'},
  {field:'scheme_name',header:'Scheme'},
  {field:'plan_name',header:'Plan'},
  {field:'opt_name',header:'Option'},
  {field:'isin_no',header:'ISIN'},
  {field:'product_code',header:'Product Code'}
 ]
}
