export class schemeClmns{
  public static COLUMNFORNFODETAILS = [
    'edit',
    'delete',
    'sl_no',
    'scheme_name',
    'scheme_type',
    'amc_name',
    'cat_name',
    'subcate_name',
    'nfo_start_dt',
    'nfo_end_dt',
    'nfo_reopen_dt',
    'sip_dates',
    'pip_fresh_min_amt',
    'pip_add_min_amt',
    'special_sip',
    'swp_dates',
    'stp_dates',
    'daily_sip_fresh_min_amt',
    'daily_sip_add_min_amt',
    'weekly_sip_fresh_min_amt',
    'weekly_sip_add_min_amt',
    'fortnightly_sip_fresh_min_amt',
    'fortnightly_sip_add_min_amt',
    'monthly_sip_fresh_min_amt',
    'monthly_sip_add_min_amt',
    'quarterly_sip_fresh_min_amt',
    'quarterly_sip_add_min_amt',
    'semi_anually_sip_fresh_min_amt',
    'semi_anually_sip_add_min_amt',
    'anually_sip_fresh_min_amt',
    'anually_sip_add_min_amt',
    'daily_swp_amt',
    'weekly_swp_amt',
    'fortnightly_swp_amt',
    'monthly_swp_amt',
    'quarterly_swp_amt',
    'semi_anually_swp_amt',
    'anually_swp_amt',
    'daily_stp_amt',
    'weekly_stp_amt',
    'fortnightly_stp_amt',
    'monthly_stp_amt',
    'quarterly_stp_amt',
    'semi_anually_stp_amt',
    'anually_stp_amt'
  ];
  public static COLUMNFORONGOINGDETAILS = [
    'edit',
    'delete',
    'sl_no',
    'scheme_name',
    'scheme_type',
    'amc_name',
    'cat_name',
    'subcate_name',
    'sip_dates',
    'pip_fresh_min_amt',
    'pip_add_min_amt',
    'special_sip',
    'swp_dates',
    'stp_dates',
    'daily_sip_fresh_min_amt',
    'daily_sip_add_min_amt',
    'weekly_sip_fresh_min_amt',
    'weekly_sip_add_min_amt',
    'fortnightly_sip_fresh_min_amt',
    'fortnightly_sip_add_min_amt',
    'monthly_sip_fresh_min_amt',
    'monthly_sip_add_min_amt',
    'quarterly_sip_fresh_min_amt',
    'quarterly_sip_add_min_amt',
    'semi_anually_sip_fresh_min_amt',
    'semi_anually_sip_add_min_amt',
    'anually_sip_fresh_min_amt',
    'anually_sip_add_min_amt',
    'daily_swp_amt',
    'weekly_swp_amt',
    'fortnightly_swp_amt',
    'monthly_swp_amt',
    'quarterly_swp_amt',
    'semi_anually_swp_amt',
    'anually_swp_amt',
    'daily_stp_amt',
    'weekly_stp_amt',
    'fortnightly_stp_amt',
    'monthly_stp_amt',
    'quarterly_stp_amt',
    'semi_anually_stp_amt',
    'anually_stp_amt'

  ];
  public static COLUMN_SUMMARY = ['edit','delete','sl_no','scheme_name','scheme_type'];
  public static COLUMN_SELECTOR = [
    {id: "edit",text:"Edit"},
    {id: "delete",text:"Delete"},
    {id: "sl_no",text:"Sl No"},
    {id: "scheme_name",text:"Scheme"},
    {id: "scheme_type",text:"Scheme Type"},
    {id: "amc_name",text:"Amc"},
    {id: "cat_name",text:"Category"},
    {id: "subcate_name",text:"Sub Category"},
    {id: "nfo_start_dt",text:"NFO Start Date"},
    {id: "nfo_end_dt",text:"NFO End Date"},
    {id: "nfo_reopen_dt",text:"NFO Reopen Date"},
     {id:'sip_dates',text:'SIP Dates'},
    {id: "pip_fresh_min_amt",text:"Fresh Amount (PIP)"},
    {id: "pip_add_min_amt",text:"Additional Amount (PIP)"},
    {id:"special_sip",text:'Special SIP'},
    {id:"swp_dates",text:'SWP Dates'},
    {id:'stp_dates',text:'STP Dates'},
    {id:'daily_sip_fresh_min_amt',text:'Daily SIP Fresh Minimum Amount'},
    {id:'daily_sip_add_min_amt',text:'Daily SIP Additional Minimum Amount'},
    {id:'weekly_sip_fresh_min_amt',text:'Weekly SIP Fresh Minimum Amount'},
    {id:'weekly_sip_add_min_amt',text:'Weekly SIP Additional Minimum Amount'},
    {id:'fortnightly_sip_fresh_min_amt',text:'Fortnightly SIP Fresh Minimum Amount'},
    {id:'fortnightly_sip_add_min_amt',text:'Fortnightly SIP Additional Minimum Amount'},
    {id:'monthly_sip_fresh_min_amt',text:'Monthly SIP Fresh Minimum Amount'},
    {id:'monthly_sip_add_min_amt',text:'Monthly SIP Additional Minimum Amount'},
    {id:'quarterly_sip_fresh_min_amt',text:'Quarterly SIP Fresh Minimum Amount'},
    {id:'quarterly_sip_add_min_amt',text:'Quarterly SIP Additional Minimum Amount'},
    {id:'semi_anually_sip_fresh_min_amt',text:'Semi Anually SIP Fresh Minimum Amount'},
    {id:'semi_anually_sip_add_min_amt',text:'Semi Anually SIP Additional Minimum Amount'},
    {id:'anually_sip_fresh_min_amt',text:'Anually SIP Fresh Minimum Amount'},
    {id:'anually_sip_add_min_amt',text:'Anually SIP Additional Minimum Amount'},
    {id:'daily_swp_amt',text:'Daily SWP Amount'},
    {id:'weekly_swp_amt',text:'Weekly SWP Amount'},
    {id:'fortnightly_swp_amt',text:'Fortnightly SWP Amount'},
    {id:'monthly_swp_amt',text:'Monthly SWP Amount'},
    {id:'quarterly_swp_amt',text:'Quarterly SWP Amount'},
    {id:'semi_anually_swp_amt',text:'Semi Anually SWP Amount'},
    {id:'anually_swp_amt',text:'Anually SWP Amount'},
    {id:'daily_stp_amt',text:'Daily STP Amount'},
    {id:'weekly_stp_amt',text:'Weekly STP Amount'},
    {id:'fortnightly_stp_amt',text:'Fortnightly STP Amount'},
    {id:'monthly_stp_amt',text:'Monthly STP Amount'},
    {id:'quarterly_stp_amt',text:'Quarterly STP Amount'},
    {id:'semi_anually_stp_amt',text:'Semi Anually STP Amount'},
    {id:'anually_stp_amt',text:'Anually STP Amount'},
  ];
}
