export class trxnClm{
  public static column = [
    {field:'sl_no',header:'Sl No'},
   {field:'bu_type',header:'Business Type'},
   {field:'branch',header:'Branch'},
   {field:'rm_name',header:'RM Name'},
   {field:'sub_brk_cd',header:'Sub Broker Code'},
   {field:'euin_no',header:'EUIN'},
   {field:'first_client_name',header:'Investor Name'},
   {field:'first_client_pan',header:'PAN'},
   {field:'trans_date',header:'Transaction Date'},
   {field:'amc_name',header:'AMC'},
   {field:'cat_name',header:'Category'},
   {field:'subcat_name',header:'Sub-Category'},
   {field:'scheme_name',header:'Scheme'},
   {field:'folio_no',header:'Folio'},
   {field:'transaction_type',header:'Transaction Type'},
   {field:'transaction_subtype',header:'Transaction Sub Type'},
   {field:'trans_no',header:'Transaction No'},
   {field:'gross_amount',header:'Gross Amount'},
   {field:'stamp_duty',header:'Stamp Duty'},
   {field:'tds',header:'TDS'},
   {field:'amount',header:'Net Amount'},
   {field:'units',header:'Unit'},
   {field:'pur_price',header:'Nav'},
   {field:'acc_no',header:'Account No'},
   {field:'bank_name',header:'Bank'},
   {field:'stt',header:'STT'},
   {field:'trans_mode',header:'Transaction Mode'},
   {field:'remarks',header:'Remarks'},
   {field:'scheme_link',header:'Scheme Link'},
   {field:'isin_link',header:'ISIN Link'}
 ]
}

