export class trxnClm{
  public static column = [
    {field:'sl_no',header:'Sl No',width:"6rem"},
   {field:'bu_type',header:'Business Type',width:"10rem"},
   {field:'branch',header:'Branch',width:"10rem"},
   {field:'rm_name',header:'RM Name',width:"16rem"},
   {field:'sub_brk_cd',header:'Sub Broker Code',width:"16rem"},
   {field:'euin_no',header:'EUIN',width:"8rem"},
   {field:'first_client_name',header:'Investor Name',width:"16rem"},
   {field:'first_client_pan',header:'PAN',width:"12rem"},
   {field:'trans_date',header:'Transaction Date',width:"9rem"},
   {field:'amc_name',header:'AMC',width:"28rem"},
   {field:'scheme_name',header:'Scheme',width:"35rem"},
   {field:'plan_name',header:'Plan',width:'14rem'},
   {field:'option_name',header:'Option',width:'14rem'},
   {field:'divident_opt',header:'IDCW Option',width:'14rem'},
   {field:'cat_name',header:'Category',width:"11rem"},
   {field:'subcat_name',header:'Sub-Category',width:"21rem"},
   {field:'folio_no',header:'Folio',width:"11rem"},
   {field:'transaction_type',header:'Transaction Type',width:"14rem"},
   {field:'transaction_subtype',header:'Transaction Sub Type',width:"14rem"},
   {field:'trans_no',header:'Transaction No',width:"11rem"},
   {field:'tot_gross_amount',header:'Gross Amount',width:"12rem"},
   {field:'tot_stamp_duty',header:'Stamp Duty',width:"8rem"},
   {field:'tot_tds',header:'TDS',width:"6rem"},
   {field:'tot_amount',header:'Net Amount',width:"12rem"},
   {field:'units',header:'Unit',width:"12rem"},
   {field:'pur_price',header:'Nav',width:"11rem"},
   {field:'bank_name',header:'Bank',width:"16rem"},
   {field:'acc_no',header:'Account No',width:"15rem"},
   {field:'stt',header:'STT',width:"6rem"},
   {field:'trans_mode',header:'Transaction Mode',width:"12rem"},
   {field:'remarks',header:'Remarks',width:"16rem"},
   {field:'amc_link',header:'AMC Link',width:"16rem"},
   {field:'scheme_link',header:'Scheme Link',width:"16rem"},
   {field:'isin_link',header:'ISIN Link',width:"16rem"},
   {field:'plan_opt',header:'Plan Option Link',width:"16rem"},
   {field:'lock_trxn',header:'Lock Status',width:"7rem"}
 ]
}

export class deleteTrxnColumn{
  public static column = [
    {field:'sl_no',header:'Sl No',width:"6rem"},
    {field:'lock_status',header:'Lock Status',width:'6rem'},
    {field:'first_client_name',header:'Investor Name',width:"16rem"},
    {field:'first_client_pan',header:'PAN',width:"9rem"},
    {field:'trans_date',header:'Transaction Date',width:"9rem"},
    {field:'amc_name',header:'AMC',width:"22rem"},
    {field:'scheme_name',header:'Scheme',width:"30rem"},
    {field:'cat_name',header:'Category',width:"11rem"},
    {field:'subcat_name',header:'Sub-Category',width:"21rem"},
    {field:'folio_no',header:'Folio',width:"11rem"},
    {field:'transaction_type',header:'Transaction Type',width:"14rem"},
    {field:'transaction_subtype',header:'Transaction Sub Type',width:"14rem"},
    {field:'trans_no',header:'Transaction No',width:"11rem"},
    {field:'gross_amount',header:'Gross Amount',width:"12rem"},
    {field:'stamp_duty',header:'Stamp Duty',width:"8rem"},
    {field:'tds',header:'TDS',width:"6rem"},
    {field:'amount',header:'Net Amount',width:"12rem"},
    {field:'units',header:'Unit',width:"12rem"},
    {field:'pur_price',header:'Nav',width:"11rem"},
    {field:'bank_name',header:'Bank',width:"16rem"},
    {field:'acc_no',header:'Account No',width:"15rem"},
    {field:'stt',header:'STT',width:"6rem"},
    {field:'trans_mode',header:'Transaction Mode',width:"12rem"},
    {field:'remarks',header:'Remarks',width:"16rem"}
  ]
}

