export interface mutualFund {
    amc_id: number
    amount: string
    app_form_scan: string
    chq_bank: number
    chq_no: string
    created_at: string
    created_by: number
    delete_flag: string
    deleted_by: any
    deleted_date: any
    email_id_outlook: any
    entry_date: string
    first_client_code: string
    first_kyc: string
    first_pan: string
    folio_no: any
    form_scan_status: any
    logged_in: any
    remarks: any
    report_scan: any
    report_send: any
    rnt_login_at: number
    rnt_login_cutt_off: any
    rnt_login_dt: any
    second_client_code: string
    second_kyc: string
    second_pan: string
    sip_end_date: string
    sip_start_date: string
    sip_status: any
    soa_date: any
    soa_sent: any
    temp_tin_id: string
    third_client_code: string
    third_kyc: string
    third_pan: string
    tin_no: string
    trans_catg: number
    trans_date: any
    trans_scheme_from: number
    trans_scheme_to: number
    trans_subcat: number
    trans_type: number
    trans_type_id: number
    unit: string
    updated_at: string
    updated_by: any
  }
  