export class mfFinClmns {

  public static  SUMMARY = [
       'edit',
       'app_frm_view',
       'branch_name',
       'entry_date',
       'tin_no',
        'sub_brk_cd',
        'euin_no',
        'first_client_name',
        'first_client_code',
        'first_client_pan',
        'trans_type',
        'scheme_name',
        'apl_no',
        'fol_no',
        'amount',
        'form_submitted_at'
   ]
   public static  SUMMARY_COPY = [

    {field:'edit',header:'Action'},
       {field:'app_frm_view',header:'Document'},
       {field:'branch_name',header:'Branch'},
       {field:'entry_date',header:'Entry Date'},
       {field:'tin_no',header:'TIN No'},
        {field:'sub_brk_cd',header:'Sub Broker Code'},
        {field:'euin_no',header:'EUIN'},
        {field:'first_client_name',header:'First Holder Name'},
        {field:'first_client_code',header:'First Holder Code'},
        {field:'first_client_pan',header:'First Holder PAN'},
        {field:'trans_name',header:'Transction Type'},
        {field:'scheme_name',header:'Scheme'},
        {field:'application_no',header:'Application No'},
        {field:'folio_no',header:'Folio No'},
        {field:'amount',header:'Amount'},
        {field:'rnt_name',header:'Form Submitted At'}
   ]

   public static  SUMMARY_COPY_SIP = [

    {field:'edit',header:'Action'},
       {field:'app_frm_view',header:'Document'},
       {field:'branch_name',header:'Branch'},
       {field:'entry_date',header:'Entry Date'},
       {field:'tin_no',header:'TIN No'},
        {field:'sub_brk_cd',header:'Sub Broker Code'},
        {field:'euin_no',header:'EUIN'},
        {field:'first_client_name',header:'First Holder Name'},
        {field:'first_client_code',header:'First Holder Code'},
        {field:'first_client_pan',header:'First Holder PAN'},
        {field:'trans_name',header:'Transction Type'},
        {field:'scheme_name',header:'Scheme'},
        {field:'application_no',header:'Application No'},
        {field:'folio_no',header:'Folio No'},
        {field:'amount',header:'Amount'},
        {field:'sip_amount',header:'SIP Amount'},
        {field:'rnt_name',header:'Form Submitted At'}
   ]



   public static  DETAILS_FOR_PIP_COLUMNS_COPY =
   [
      {field:'edit',header:'Action'},
      {field:'app_frm_view',header:'Document'},
       {field:'branch_name',header:'Branch'},
       {field:'entry_date',header:'Entry Date'},
       {field:'tin_no',header:'TIN No'},
       {field:'bu_type',header:'Business Type'},
       {field:'arn_no',header:'ARN No'},
        {field:'sub_brk_cd',header:'Sub Broker Code'},
        {field:'euin_no',header:'EUIN'},
        {field:'first_client_name',header:'First Holder Name'},
        {field:'first_client_code',header:'First Holder Code'},
        {field:'first_client_pan',header:'First Holder PAN'},
        {field:'first_client_kyc_status',header:'First Holder KYC Status'},
        {field:'mode_of_holding',header:'Mode Of Holding'},
        {field:'second_client_name',header:'Second Holder Name'},
        {field:'second_client_code',header:'Second Holder Code'},
        {field:'second_client_pan',header:'Second Holder PAN'},
        {field:'second_client_kyc_status',header:'Second Holder KYC Status'},
        {field:'third_client_name',header:'Third Holder Name'},
        {field:'third_client_code',header:'Third Holder Code'},
        {field:'third_client_pan',header:'Third Holder PAN'},
        {field:'third_client_kyc_status',header:'Third Holder KYC Status'},
        {field:'trans_name',header:'Transaction Type'},
        {field:'scheme_name',header:'Scheme'},
        {field:'plan_name',header:'Plan'},
        {field:'opt_name',header:'Option'},
        {field:'amount',header:'Amount'},
        {field:'chq_no',header:'Cheque No'},
        {field:'bank',header:'Bank'},
        {field:'inv_type',header:'Investment Type'},
        {field:'application_no',header:'Application No'},
        {field:'folio_no',header:'Folio No'},
        {field:'rnt_name',header:'Form Submitted At'},
        {field:'remarks',header:'Remarks'}
   ]

   public static  DETAILS_FOR_SIP_COLUMNS_COPY =
   [
      {field:'edit',header:'Action'},
      {field:'app_frm_view',header:'Document'},
       {field:'branch_name',header:'Branch'},
       {field:'entry_date',header:'Entry Date'},
       {field:'tin_no',header:'TIN No'},
       {field:'bu_type',header:'Business Type'},
       {field:'arn_no',header:'ARN No'},
        {field:'sub_brk_cd',header:'Sub Broker Code'},
        {field:'euin_no',header:'EUIN'},
        {field:'first_client_name',header:'First Holder Name'},
        {field:'first_client_code',header:'First Holder Code'},
        {field:'first_client_pan',header:'First Holder PAN'},
        {field:'first_client_kyc_status',header:'First Holder KYC Status'},
        {field:'mode_of_holding',header:'Mode Of Holding'},
        {field:'second_client_name',header:'Second Holder Name'},
        {field:'second_client_code',header:'Second Holder Code'},
        {field:'second_client_pan',header:'Second Holder PAN'},
        {field:'second_client_kyc_status',header:'Second Holder KYC Status'},
        {field:'third_client_name',header:'Third Holder Name'},
        {field:'third_client_code',header:'Third Holder Code'},
        {field:'third_client_pan',header:'Third Holder PAN'},
        {field:'third_client_kyc_status',header:'Third Holder KYC Status'},
        {field:'trans_name',header:'Transaction Type'},
        {field:'scheme_name',header:'Scheme'},
        {field:'plan_name',header:'Plan'},
        {field:'opt_name',header:'Option'},
        {field:'amount',header:'Amount'},
        {field:'chq_no',header:'Cheque No'},
        {field:'bank',header:'Bank'},
        {field:'inv_type',header:'Investment Type'},
        {field:'application_no',header:'Application No'},
        {field:'folio_no',header:'Folio No'},
        {field:'sip_type_name',header:'SIP Type'},
        {field:'sip_frequency',header:'SIP Frequency'},
        {field:'sip_date',header:'SIP Date'},
        {field:'sip_start_date',header:'SIP Start Date'},
        {field:'sip_end_date',header:'SIP End Date'},
        {field:'sip_amount',header:'SIP Amount'},
        {field:'rnt_name',header:'Form Submitted At'},
        {field:'remarks',header:'Remarks'}
   ]


   public static  DETAILS_FOR_PIP_COLUMNS =
   [
      'edit',
      'app_frm_view',
       'branch_name',
       'entry_date',
       'tin_no',
       'bu_type',
       'arn_no',
        'sub_brk_cd',
        'euin_no',
        'first_client_name',
        'first_client_code',
        'first_client_pan',
        'first_client_kyc_status',
        'mode_of_holding',
        'second_client_name',
        'second_client_code',
        'second_client_pan',
        'second_client_kyc_status',
        'third_client_name',
        'third_client_code',
        'third_client_pan',
        'third_client_kyc_status',
        'trans_type',
        'scheme_name',
        'plan_name',
        'opt_name',
        'amount',
        'chq_no',
        'bank',
        'inv_type',
        'apl_no',
        'fol_no',
        'form_submitted_at',
        'remarks'
   ]


   public static  DETAILS_FOR_SWITCH_COLUMNS_COPY =
   [
    {field:'edit',header:'Action'},
    {field:'app_frm_view',header:'Document'},
       {field:'branch_name',header:'Branch'},
       {field:'entry_date',header:'Entry Date'},
       {field:'tin_no',header:'TIN No'},
       {field:'bu_type',header:'Business Type'},
       {field:'arn_no',header:'ARN No'},
        {field:'sub_brk_cd',header:'SubBroker Code'},
        {field:'euin_no',header:'EUIN'},
        {field:'first_client_name',header:'First Holder Name'},
        {field:'first_client_code',header:'First Holder Code'},
        {field:'first_client_pan',header:'First Holder PAN'},
        {field:'first_client_kyc_status',header:'First Holder KYC Status'},
        {field:'mode_of_holding',header:'Mode Of Holding'},
        {field:'second_client_name',header:'Second Holder Name'},
        {field:'second_client_code',header:'Second Holder Code'},
        {field:'second_client_pan',header:'Second Holder PAN'},
        {field:'second_client_kyc_status',header:'Second Holder KYC Status'},
        {field:'third_client_name',header:'Third Holder Name'},
        {field:'third_client_code',header:'Third Holder Code'},
        {field:'third_client_pan',header:'Third Holder PAN'},
        {field:'third_client_kyc_status',header:'Third Holder KYC Status'},
        {field:'trans_name',header:'Transaction Type'},
        {field:'scheme_name',header:'Scheme'},
        {field:'plan_name',header:'Plan'},
        {field:'opt_name',header:'Option'},
        {field:'scheme_name_to',header:'Scheme Name (To Scheme)'},
        {field:'amount',header:'Amount'},
        {field:'chq_no',header:'Cheque No'},
        {field:'bank',header:'Bank'},
        {field:'inv_type',header:'Investment Type'},
        {field:'application_no',header:'Application No'},
        {field:'folio_no',header:'Folio No'},
        {field:'rnt_name',header:'Form Submitted At'},
        {field:'remarks',header:'Remarks'}
   ]

   public static  DETAILS_FOR_SWITCH_COLUMNS =
   [
    'edit',
    'app_frm_view',
       'branch_name',
       'entry_date',
       'tin_no',
       'bu_type',
       'arn_no',
        'sub_brk_cd',
        'euin_no',
        'first_client_name',
        'first_client_code',
        'first_client_pan',
        'first_client_kyc_status',
        'mode_of_holding',
        'second_client_name',
        'second_client_code',
        'second_client_pan',
        'second_client_kyc_status',
        'third_client_name',
        'third_client_code',
        'third_client_pan',
        'third_client_kyc_status',
        'trans_type',
        'scheme_name',
        'plan_name',
        'opt_name',
        'scheme_name_to',
        'amount',
        'chq_no',
        'bank',
        'inv_type',
        'apl_no',
        'fol_no',
        'form_submitted_at',
        'remarks'
   ]
   public static COLUMN_SELECTOR=
    [
      {field:'edit',header:'Action'},
      {field:'app_frm_view',header:'Document'},
      {field:'branch_name',header:'Branch Name'},
       {field:'entry_date',header:'Entry Date'},
       {field:'tin_no',header:'TIN No.'},
       {field:'bu_type',header:'Business Type'},
       {field:'arn_no',header:'ARN No'},
        {field:'sub_brk_cd',header:'Sub Broker Code'},
        {field:'euin_no',header:'EUIN'},
        {field:'first_client_name',header:'First Holder Name'},
        {field:'first_client_code',header:'First Holder Code'},
        {field:'first_client_pan',header:'First Holder PAN'},
        {field:'first_client_kyc_status',header:'First Holder KYC Status'},
        {field:'mode_of_holding',header:'Mode Of Holding'},
        {field:'second_client_name',header:'Second Holder Name'},
        {field:'second_client_code',header:'Second Holder Code'},
        {field:'second_client_pan',header:'Second Holder PAN'},
        {field:'second_client_kyc_status',header:'Second Holder KYC Status'},
        {field:'third_client_name',header:'Third Holder Name'},
        {field:'third_client_code',header:'Third Holder Code'},
        {field:'third_client_pan',header:'Third Holder PAN'},
        {field:'third_client_kyc_status',header:'Third Holder KYC Status'},
        {field:'trans_name',header:'Transaction Type'},
        {field:'scheme_name',header:'Scheme name'},
        {field:'plan_name',header:'Plan'},
        {field:'opt_name',header:'Option'},
        {field:'scheme_name_to',header:'Scheme name (To Scheme)'},
        {field:'amount',header:'Amount'},
        {field:'chq_no',header:'Cheque No.'},
        {field:'bank',header:'Bank'},
        {field:'inv_type',header:'Investment Type'},
        {field:'application_no',header:'Application No'},
        {field:'folio_no',header:'Folio No.'},
        {field:'sip_type_name',header:'SIP Type'},
        {field:'sip_frequency',header:'SIP Frequency'},
        {field:'sip_date',header:'SIP Date'},
        {field:'sip_start_date',header:'SIP Start Date'},
        {field:'sip_end_date',header:'SIP End Date'},
        {field:'sip_amount',header:'SIP Amount'},
        {field:'rnt_name',header:'Form Submitted At'},
        {field:'remarks',header:'Remarks'}
    ];
}
