export class nfoClmns {
  public static SUMMARY_COPY = [
    {field:'folio_no',header:'Folio No.',width:'8rem'},
    {field:'ack_copy_scan',header:'ACK. View',width:'7rem'},

    {field:'edit',header:'Edit',width:'3rem'},
    { field: 'app_frm_view', header: 'APP View',width:'8rem'},
    {field:'entry_date',header:'Entry Date',width:'8rem'},
    { field: 'rnt_login_cutt_off', header: 'Login Cut Off' ,width:'7rem'},
    { field: 'rnt_login_dt', header: 'Login Date&Time',width:'15rem'},
    {field:'tin_no',header:'TIN',width:'8rem'},
    {field:'branch_name',header:'Branch',width:'10rem'},
    {field:'sub_brk_cd',header:'Sub Broker Code',width:'12rem'},
    {field:'euin_no',header:'EUIN',width:'7rem'},
    {field:'first_client_name',header:'First Holder Name',width:'18rem'},
    {field:'first_client_code',header:'First Holder Code',width:'8rem'},
    {field:'first_client_pan',header:'First Holder PAN',width:'8rem'},
    {field:'trans_name',header:'Transction Type',width:'12rem'},
    {field:'scheme_name',header:'Scheme',width:'25rem'},
    {field:'plan_name',header:'Plan',width:'10rem'},
    {field:'opt_name',header:'Option',width:'10rem'},

    {field:'application_no',header:'Application No',width:'10rem'},
    // { field: 'folio_no', header: 'Folio No' },
    {field:'amount',header:'Amount',width:'8rem'},
            {field:'rnt_name',header:'Form Submitted At',width:'15rem'},
    {field:'manual_trans_status',header:'Transaction Status',width:'8rem'},
    {field:'manual_update_remarks',header:'Transaction Remarks',width:'10rem'}
          ];
  public static SUMMARY_COPY_SIP = [
    {field:'folio_no',header:'Folio No.',width:'8rem'},
    {field:'ack_copy_scan',header:'ACK. View',width:'7rem'},
    {field:'edit',header:'Edit',width:'3rem'},
    { field: 'app_frm_view', header: 'APP View',width:'8rem'},
    {field:'entry_date',header:'Entry Date',width:'8rem'},
    { field: 'rnt_login_cutt_off', header: 'Login Cut Off' ,width:'7rem'},
    { field: 'rnt_login_dt', header: 'Login Date&Time',width:'15rem'},
    {field:'tin_no',header:'TIN',width:'8rem'},
    {field:'branch_name',header:'Branch',width:'10rem'},
            {field:'sub_brk_cd',header:'Sub Broker Code',width:'12rem'},
    {field:'euin_no',header:'EUIN',width:'7rem'},
            {field:'first_client_name',header:'First Holder Name',width:'18rem'},
            {field:'first_client_code',header:'First Holder Code',width:'8rem'},
            {field:'first_client_pan',header:'First Holder PAN',width:'8rem'},
            {field:'trans_name',header:'Transction Type',width:'12rem'},
            {field:'scheme_name',header:'Scheme',width:'25rem'},
            {field:'application_no',header:'Application No',width:'10rem'},
    { field: 'folio_no', header: 'Folio No' },
    {field:'amount',header:'Amount',width:'8rem'},
    { field: 'sip_amount', header: 'SIP Amount' },
            {field:'rnt_name',header:'Form Submitted At',width:'15rem'},
    {field:'manual_trans_status',header:'Transaction Status',width:'8rem'},
    {field:'manual_update_remarks',header:'Transaction Remarks',width:'10rem'}
          ];
public static COLUMN_SELECTOR=[
  {field:'folio_no',header:'Folio No.',width:'8rem'},
  {field:'ack_copy_scan',header:'ACK. View',width:'7rem'},
  {field:'edit',header:'Edit',width:'5rem'},
  {field:'app_frm_view',header:'APP View',width:'7rem'},
  {field:'entry_date',header:'Entry Date',width:'7rem'},
   { field: 'rnt_login_cutt_off', header: 'Login Cut Off' ,width:'7rem'},
    { field: 'rnt_login_dt', header: 'Login Date&Time',width:'15rem'},
    {field:'tin_no',header:'TIN',width:'8rem'},
    {field:'bu_type',header:'Business Type',width:'8rem'},
    {field:'branch_name',header:'Branch',width:'10rem'},
    {field:'rm_name',header:'RM Name',width:'8rem'},
    {field:'sub_brk_cd',header:'Sub Broker Code',width:'12rem'},
    {field:'euin_no',header:'EUIN',width:'7rem'},
    {field:'first_client_name',header:'First Holder Name',width:'18rem'},
    {field:'first_client_code',header:'First Holder Code',width:'8rem'},
    {field:'first_client_pan',header:'First Holder PAN',width:'10rem'},
    {field:'first_kyc',header:'First Holder KYC Status',width:'10rem'},
    {field:'mode_of_holding',header:'Mode Of Holding',width:'12rem'},
    {field:'second_client_name',header:'Second Holder Name',width:'18rem'},
    {field:'second_client_code',header:'Second Holder Code',width:'12rem'},
    {field:'second_client_pan',header:'Second Holder PAN',width:'8rem'},
    {field:'second_kyc',header:'Second Holder KYC Status',width:'10rem'},
    {field:'third_client_name',header:'Third Holder Name',width:'15rem'},
    {field:'third_client_code',header:'Third Holder Code',width:'12rem'},
    {field:'third_client_pan',header:'Third Holder PAN',width:'8rem'},
    {field:'third_kyc',header:'Third Holder KYC Status',width:'10rem'},
    {field:'trans_name',header:'Transaction Type',width:'15rem'},
  {field:'manual_trans_status',header:'Transaction Status',width:'8rem'},
  {field:'manual_update_remarks',header:'Transaction Remarks',width:'10rem'}
  ]
public static DETAILS_PIP=[
  {field:'scheme_name',header:'Scheme',width:'25rem'},
  {field:'plan_name',header:'Plan',width:'10rem'},
  {field:'opt_name',header:'Option',width:'10rem'},
  {field:'inv_type',header:'Investment Type',width:'15rem'},
  {field:'application_no',header:'Application No',width:'12rem'},
  {field:'folio_no',header:'Folio No.',width:'8rem'},
  {field:'plan_name',header:'Plan',width:'10rem'},
  {field:'opt_name',header:'Option',width:'10rem'},
  {field:'amount',header:'Amount',width:'10rem'},
  {field:'chq_no',header:'Cheque No',width:'10rem'},
  {field:'bank_name',header:'Bank',width:'12rem'},
  {field:'rnt_name',header:'Form Submitted At',width:'10rem'},
  {field:'remarks',header:'Remarks',width:'10rem'},
  {field:'manual_trans_status',header:'Transaction Status',width:'8rem'},
  {field:'manual_update_remarks',header:'Transaction Remarks',width:'10rem'}
]
public static DETAILS_SIP=[
  {field:'scheme_name',header:'Scheme',width:'25rem'},
  {field:'plan_name',header:'Plan',width:'10rem'},
  {field:'opt_name',header:'Option',width:'10rem'},
  {field:'inv_type',header:'Investment Type',width:'15rem'},
  {field:'application_no',header:'Application No',width:'12rem'},
  // {field:'folio_no',header:'Folio No.',width:'8rem'},
  {field:'plan_name',header:'Plan',width:'10rem'},
  {field:'opt_name',header:'Option',width:'10rem'},
  {field:'sip_type_name',header:'SIP Type',width:'12rem'},
  {field:'sip_frequency',header:'SIP Frequency',width:'12rem'},
  {field:'sip_date',header:'SIP Date',width:'12rem'},
  {field:'sip_start_date',header:'SIP Start Date',width:'12rem'},
  {field:'sip_end_date',header:'SIP End Date',width:'12rem'},
  {field:'sip_amount',header:'SIP Amount',width:'12rem'},
  {field:'amount',header:'Amount',width:'12rem'},
  {field:'chq_no',header:'Cheque No',width:'12rem'},
  {field:'bank_name',header:'Bank',width:'15rem'},
  {field:'rnt_name',header:'Form Submitted At',width:'12rem'},
  {field:'remarks',header:'Remarks',width:'10rem'},
  {field:'manual_trans_status',header:'Transaction Status',width:'8rem'},
  {field:'manual_update_remarks',header:'Transaction Remarks',width:'10rem'}
]
public static DETAILS_SWITCH = [
  {field:'scheme_name',header:'Scheme Name (From Scheme)',width:'20rem'},
  {field:'plan_name',header:'Plan (From Scheme)',width:'10rem'},
  {field:'opt_name',header:'Option (From Scheme)',width:'10rem'},
  {field:'scheme_name_to',header:'Scheme Name (To Scheme)',width:'20rem'},
  {field:'plan_name_to',header:'Plan (To Scheme)',width:'10rem'},
  {field:'opt_name_to',header:'Option (To Scheme)',width:'10rem'},
  // {field:'folio_no',header:'Folio No.',width:'8rem'},
  {field:'amount',header:'Amount',width:'10rem'},
  {field:'unit',header:'Unit',width:'8rem'},
  {field:'rnt_name',header:'Form Submitted At',width:'10rem'},
  {field:'remarks',header:'Remarks',width:'10rem'},
  {field:'manual_trans_status',header:'Transaction Status',width:'8rem'},
  {field:'manual_update_remarks',header:'Transaction Remarks',width:'10rem'}
]
public static DETAILS_NFOCOMBO=[
  {field:'scheme_name',header:'Scheme (From Scheme)',width:'25rem'},
  {field:'plan_name',header:'Plan (From Plan)',width:'10rem'},
  {field:'opt_name',header:'Option (From Option)',width:'10rem'},
  {field:'scheme_name_to',header:'Scheme Name (To Scheme)',width:'20rem'},
  {field:'plan_name_to',header:'Plan (To Plan)',width:'10rem'},
  {field:'opt_name_to',header:'Option (To Option)',width:'10rem'},
  {field:'inv_type',header:'Investment Type',width:'15rem'},
  {field:'application_no',header:'Application No',width:'12rem'},
  // {field:'folio_no',header:'Folio No.',width:'8rem'},
  {field:'chq_no',header:'Cheque No',width:'10rem'},
  {field:'bank_name',header:'Bank',width:'12rem'},
  {field:'first_inv_amount',header:'Amount',width:'10rem'},
  
  {field:'switch_amt',header:'Switch Amount / Unit',width:'12rem'},
  {field:'rnt_name',header:'Form Submitted At',width:'10rem'},
  {field:'remarks',header:'Remarks',width:'10rem'},
  {field:'manual_trans_status',header:'Transaction Status',width:'8rem'},
  {field:'manual_update_remarks',header:'Transaction Remarks',width:'10rem'}
]
}
