export class mfRcvClmns {
  // public static INITIAL_CLMNS = [
  //   'edit',
  //   'delete',
  //   'sl_no',
  //   'temp_tin_no',
  //   'bu_type',
  //   'branch_name',
  //   'entry_dt',
  //   'euin_no',
  //   'client_name',
  //   'client_code',
  //   'rcv_datetime',
  //   'recv_from',
  //   'trans_type',
  // ];
  // public static DETAIL_CLMNS = [
  //   'edit',
  //   'delete',
  //   'sl_no',
  //   'temp_tin_no',
  //   'bu_type',
  //   'branch_name',
  //   'entry_dt',
  //   'arn_no',
  //   'sub_brk_cd',
  //   'euin_no',
  //   'client_name',
  //   'client_code',
  //   'rcv_datetime',
  //   'recv_from',
  //   'trans_type',
  //   'apl_no',
  //   'folio_no',
  //   'remarks',
  // ];

  // public static CLOUMN_SELECTOR = [
  //   { id: 'edit', text: 'Edit' },
  //   { id: 'delete', text: 'Delete' },
  //   { id: 'sl_no', text: 'Sl No' },
  //   { id: 'temp_tin_no', text: 'Temporary Tin Number' },
  //   { id: 'bu_type', text: 'Buisness type' },
  //   { id: 'branch_name', text: 'Branch' },
  //   { id: 'entry_dt', text: 'Entry Date' },
  //   { id: 'arn_no', text: 'ARN Number' },
  //   { id: 'sub_brk_cd', text: 'Sub Broker Code' },
  //   { id: 'euin_no', text: 'EUIN' },
  //   { id: 'client_name', text: 'First Holder Name' },
  //   { id: 'client_code', text: 'First Holder Code' },
  //   { id: 'rcv_datetime', text: 'Receive DateTime' },
  //   { id: 'recv_from', text: 'Reaceive From' },
  //   { id: 'trans_type', text: 'Transaction Type' },
  //   { id: 'apl_no', text: 'Application Number' },
  //   { id: 'folio_no', text: 'Folio Number' },
  //   { id: 'remarks', text: 'Remarks' },
  // ];
  public static COLUMN_SELECTOR =[
      { field: 'edit', header: 'Edit' },
    { field: 'delete', header: 'Delete' },
    { field: 'entry_date', header: 'Entry Date' },
    { field: 'temp_tin_no', header: 'Temporary Tin' },
    { field: 'bu_type', header: 'Business type' },
    { field: 'branch_name', header: 'Branch' },
    { field: 'rm_name', header: 'RM Name' },
    { field: 'sub_brk_cd', header: 'Sub Broker Code' },
    { field: 'euin_no', header: 'EUIN' },
    { field: 'client_name', header: 'First Holder Name' },
    { field: 'client_code', header: 'First Holder Code' },
    { field: 'trans_name', header: 'Transaction Type' },
    {field:'scheme_name',header:'Scheme'},
    { field: 'application_no', header: 'Application Number' },
    { field: 'folio_no', header: 'Folio Number' },
    { field: 'rec_datetime', header: 'Receive DateTime' },
    { field: 'recv_from', header: 'Reaceive From' },
    { field: 'remarks', header: 'Remarks' },
  ]

  public static SUMMARY = [
     {field:'edit',header:'Edit'},
    {field:'delete',header:'Delete'},
    {field:'entry_date',header:'Entry Date'},
    {field:'temp_tin_no',header:'Temporary TIN'},
    {field:'bu_type',header:'Business Type'},
    {field:'branch_name',header:'Branch'},
    {field:'rm_name',header:'RM Name'},
    {field:'euin_no',header:'EUIN'},
    {field:'client_name',header:'First Holder Name'},
    {field:'scheme_name',header:'Scheme'},
    {field:'rec_datetime',header:'Receive DateTime'},
    {field:'recv_from',header:'Reaceive From'}
  ]
}
